<?php
    header("Content-type: text/css; charset: UTF-8");
?>
/*
Title:   IE Fixes Css File
Author:  http://themeforest.net/user/hogash // Marius Hogas
Description: This is the stylesheet that holds the fixes for the IE (the stupidest browsers ever made)  */
.oldie .selectorsBlock.bullets .selectors .item,
.oldie .topnav li.drop .inner,
.oldie #search .search,
.oldie #search form input[type=text],
.oldie .info_pop,
.oldie .playVideo,
.oldie .social-icons li a:hover,
.oldie .black_border,
.oldie .white_border,
.oldie .loupe,
.oldie #sliding_panel,
.oldie .theHoverBorder,
.oldie .theHoverBorder:hover,
.oldie .slidingDetails:hover,
.oldie .recentwork_carousel.style2 li a .details .plus,
.oldie .gobox:hover,
.oldie .info-text,
.oldie .circlehover,
.oldie .circlehover[data-position="bottom-right"],
.oldie .circlehover:hover,
.oldie .testimonial_box blockquote,
.oldie .pricing_table .pr_table_col,
.oldie .pricing_table .pr_table_col:hover,
.oldie .pricing_table .pr_table_col.caption_column,
.oldie .process_box,
.oldie .process_box:hover,
.oldie .timeline_box:hover,
.oldie .services_box.style2 .box:hover,
.oldie .eBlog .itemContainer,
.oldie .hg-portfolio-sortable ul#thumbs li .inner-item:hover,
.oldie .ptcarousel,
.oldie .product-list-item > .hover,
.oldie .product-list-item:hover > .hover,
.oldie .adbox.video:after,
.oldie .btn-flat,
.oldie .topnav > li > a,
.oldie .circle_title > span ,
.oldie .login-panel .login_facebook,
.oldie .theHoverBorder,
.oldie .tabs_style3,
.oldie .partners_carousel li a,
.oldie .infobox1,
.oldie .infobox2,
.oldie .feature_box.style2 span.icon,
.oldie .services_box .icon,
.oldie .latest_posts.default-style .hoverBorder h6,
.oldie .gobox,
.oldie .circlehover,
.oldie .circlehover:before,
.oldie .acc-group.style2,
.oldie .screenshot-box,
.oldie .social-share.colored li,
.oldie #twitterFeed,
.oldie .vertical_tabs,
.oldie .pricing_table.rounded-corners .highlight,
.oldie .process_box .number,
.oldie .process_box[data-align=right] .number,
.oldie #sidebar,
.oldie #sidebar ul.menu li a,
.oldie .services_box.style2 .box .icon,
.oldie .hg-portfolio-item .other-images li iframe,
.oldie .btn-flat,
.oldie .show-grid [class*="span"]
{behavior:url(<?php echo $_GET['p']; ?>/js/PIE.htc);}
